### ISSUE TITLE
rubocop導入方法について調査・確認

### ISSUE THREAD

**Issue by SabaCrevette** [SabaCrevette/travel_app#14]
- [x] rubocopの導入方法の確認

**Comment by SabaCrevette** [comment]
# Rubocopの機能
## Rubyのコードスタイルと静的解析ツール
- コードスタイルのチェック（一貫性のあるスタイルを保つ）
- 静的解析（コードのバグ、不要なコード、書式の問題などを識別）
- 自動修正（一部のスタイル違反やコードの問題を自動修正）

## 参考サイト
- [公式](https://github.com/rubocop/rubocop)
- [公式ドキュメント](https://docs.rubocop.org/rubocop/)
- [【Rails】rubocop導入手順の備忘録](e2e12bb503fe56404329)
- [【Rails】ついついrubocopを通し忘れてしまう全ての方へ！commitと同時に自動でrubocopを通す設定方法！](https://qiita.com/kumaryoya/items/9c9d42ca8b3ff46565ce)

## コマンドについて
- `rubocop`　基本コマンド
- `rubocop -a` 自動修正可能な違反については自動修正
- `rubocop -A` より積極的な自動修正、多くの違反を修正する可能性もあるので注意

## 導入時
- `gem 'rubocop', require: false`
  require: falseにより自動的にロードされるのを防ぐ
- `bundle install`と`bundle exec rubocop`で実行テスト
- `.rubocop.yml`の追加、rubocopの設定追記（カリキュラム参照）

## git commit時にrubocopを行う設定
- `brew install lefthook`
- `lefthook install`

```
#lefthook.yml（commitと同時にrubocopを通す設定）
pre-commit:
  parallel: true
  commands:
    rubocop:
      run: bundle exec rubocop
```

- `lefthook add pre-commit` ファイル内容の反映

[![Image from Gyazo](https://i.gyazo.com/25126113406e2be64c8913bcd2250605.png)](https://gyazo.com/25126113406e2be64c8913bcd2250605)
